name: freestyletarot
region: sgp
services:
  - name: backend
    github:
      branch: main
      deploy_on_push: true
      repo: BitCd7139/FreeStyleTarot
    instance_count: 1
    instance_size_slug: basic-xxs
    source_dir: /
    run_command: bin/FreeStyleTarot
    http_port: 8080
    envs:
      - key: PORT
        scope: RUN_TIME
        value: "8080"
    routes:
      - path: /api

static_sites:
  - name: frontend
    github:
      branch: main
      deploy_on_push: true
      repo: BitCd7139/FreeStyleTarot
    source_dir: /web
    build_command: npm install && npm run build
    output_dir: dist
    routes:
      - path: /          # 前端路由